app_1/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth import views as auth_views
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login/$', login, name='login-data'),
    url(r'^logout/$', logout, name='logout'),
]

app_2/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', register_page, name='register'),
    url(r'^register/submit/$', register_narasumber, name='register-narasumber'),
    url(r'^validate-username/$', check_username, name='validate-username'),
    url(r'^validate-npm/$', check_npm, name='validate-npm'),
    url(r'^validate-pwd/$', validate_pwd, name='validate-pwd'),
]

bmnc5d/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import app_6.urls as app_6
import app_7.urls as app_7
import app_8.urls as app_8
import app_1.urls as app_1
import app_2.urls as app_2
import app_3.urls as app_3
import app_4.urls as app_4
import app_5.urls as app_5

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(app_6)),
    url(r'^newsbyuser/', include(app_7)),
    url(r'^polling/', include(app_8)),
    url(r'^login/', include(app_1)),   
    url(r'^register/', include(app_2)), 
    url(r'^addBerita/', include(app_3)), 
    url(r'^polling_berita/', include(app_4)),
    url(r'^polling_biasa/', include(app_5)),
]

app_2/models.py
from django.db import models
import datetime
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Create your models here.
class Universitas(models.Model):
    id = models.IntegerField(primary_key=True)
    jalan = models.CharField(max_length=100)
    kelurahan = models.CharField(max_length=50)
    provinsi = models.CharField(max_length=50)
    kodepos = models.CharField(max_length=10)
    website = models.CharField(max_length=50)

    class Meta:
        managed = True
        db_table = 'universitas'

class Narasumber(models.Model):
    id = models.IntegerField(primary_key=True)
    nama = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    tempat = models.CharField(max_length=50)
    tanggal = models.CharField(max_length=50)
    no_hp = models.CharField(max_length=50)
    jumlah_berita = models.IntegerField(blank=True, null=True)
    rerata_kata = models.IntegerField(blank=True, null=True)
    id_universitas = models.ForeignKey('Universitas', models.DO_NOTHING, db_column='id_universitas')
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'narasumber'

class Mahasiswa(models.Model):
    id_narasumber = models.ForeignKey('Narasumber', models.DO_NOTHING, db_column='id_narasumber', primary_key=True)
    npm = models.CharField(max_length=20)
    status = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'mahasiswa'

class Dosen(models.Model):
    id_narasumber = models.ForeignKey('Narasumber', models.DO_NOTHING, db_column='id_narasumber', primary_key=True)
    nik_dosen = models.CharField(max_length=20)
    jurusan = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'dosen'

class Staf(models.Model):
    id_narasumber = models.ForeignKey(Narasumber, models.DO_NOTHING, db_column='id_narasumber', primary_key=True)
    nik_staf = models.CharField(max_length=20)
    posisi = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'staf'

app_2/forms.py
from django import forms
from .models import *

class MyModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        text = "University #"+str(obj.id)+" - "+str(obj.website)
        return text

class RegisterForm(forms.Form):
    role = {
        ('', '---------------'),
        ('dosen', 'Dosen'),
        ('staf', 'Staf'),
        ('mahasiswa', 'Mahasiswa'),
    }
    status = {
        ('', '---------------'),
        ('aktif', 'Aktif'),
        ('tidak', 'Tidak Aktif'),
    }
    error_message = {
        'required': 'This field is required to fill',
    }
    username = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter your username',
    }
    password = {
        'type': 'password',
        'class': 'form-control',
        'placeholder': 'Minimal 8 characters',
    }
    nomor_identitas = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter your NIK/NPM',
        'disabled':'true'
    }
    nama = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter your full name',
    }
    tempat_lahir = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter your birth place',
    }
    tanggal_lahir = {
        'type': 'date',
        'class': 'form-control',
    }
    email = {
        'type': 'email',
        'class': 'form-control',
        'placeholder': 'Enter your valid email adress',
    }
    no_hp = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter a valid phone number',
    }
    jurusan = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter your major. Ex: Information System, Computer Science, etc.',
        'disabled':'true'
    }
    posisi = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Enter your position. Ex: Administrator, Human Resources, etc.',
        'disabled':'true'
    }

    jurusan = forms.CharField(label='Jurusan', required=False, max_length=50, widget=forms.TextInput(attrs=jurusan))
    posisi = forms.CharField(label='Posisi', required=False, max_length=50, widget=forms.TextInput(attrs=posisi))

    username = forms.CharField(label='Username', required=True, max_length=50, widget=forms.TextInput(attrs=username))
    password = forms.CharField(label='Password', required=True, max_length=50, widget=forms.TextInput(attrs=password))

    nama = forms.CharField(label='Full Name', required=True, max_length=50, widget=forms.TextInput(attrs=nama))
    email = forms.CharField(label='Email adress', required=True, max_length=50, widget=forms.TextInput(attrs=email))
    tempat = forms.CharField(label='Tempat Lahir', required=True, max_length=50, widget=forms.TextInput(attrs=tempat_lahir))
    tanggal = forms.DateTimeField(label='Birthday Date', required=True, widget=forms.DateInput(attrs=tanggal_lahir))
    no_hp = forms.CharField(label='Phone Number', max_length=50,required=False, widget=forms.TextInput(attrs=no_hp))
    nomor_identitas = forms.CharField(label='Identity Number (NPM,NIK)', required=True, max_length=20, widget=forms.TextInput(attrs=nomor_identitas))

    role = forms.ChoiceField(label='Role', choices=role, required=True, widget=forms.Select(attrs={'class':'form-control'}))
    status = forms.ChoiceField(label='Status Kemahasiswaan', required=False, choices=status, widget=forms.Select(attrs={'class':'form-control','disabled':'true'}))
    id_universitas = MyModelChoiceField(queryset=Universitas.objects.all().order_by('id'), required=True, empty_label="Select your university", label='ID Universitas', widget=forms.Select(attrs={'class':'form-control','disabled':'true'}))
    #id_universitas = forms.MyModelChoiceField(queryset=Universitas.objects.all().order_by('id'), label='ID Universitas', required=True, widget=forms.Select(attrs={'class':'form-control'}))

app_2/views.py
from django.shortcuts import render, redirect, reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import *
from .forms import *
from django.db import connection
from django.contrib import messages
# Create your views here.
response={}

def register_page(request):
    response['cek'] = "Halaman register"
    response['reg_form'] = RegisterForm
    return render(request, 'app_2/register.html', response)

def hasNumbers(inputString):
	return any(char.isdigit() for char in inputString)

def hasLetter(inputString):
    return any(c.isalpha() for c in inputString)

@csrf_exempt
def validate_pwd(request):
    if request.method == "POST":
        password = request.POST.get('password', False)
        notif = ""
        list = []
        length = len(password)
        if (length<8):
            notif = "Panjang password minimal 8 karakter"
            list.append(notif)
        if (hasNumbers(password)==False):
            notif = "Password harus mengandung angka"
            list.append(notif)
        if (hasLetter(password)==False):
            notif="Password harus mengandung huruf"
            list.append(notif)
        print(list)
        data = {
            'list_of_notif' : list
        }
        return JsonResponse(data)


@csrf_exempt
def check_username(request):
    if request.method == 'POST':
        username = request.POST.get('username', False)
        cursor = connection.cursor()
        cursor.execute('select count(*) from narasumber')
        count = cursor.fetchone()[0] #(2,)
        taken = False
        if(count>0):
            cursor.execute('select username from narasumber')
            username_users = cursor.fetchall()#(delfa,)(salvi,)
            print(username_users[0][0])
            for p in username_users:
                print(str(p[0])+" dan "+str(username))
                if p[0] == username:
                    taken = True
                    break
                else:
                    taken = False
        else:
            taken = False
        data = {
            'uname_is_taken' : taken
        }
        return JsonResponse(data)

@csrf_exempt
def check_npm(request):
    if request.method == 'POST':
        nomor_identitas = request.POST.get('npm', False)
        role = request.POST.get('role', False)
        cursor = connection.cursor()
        taken = False
        no_role = False
        if role == 'dosen':
            cursor.execute('select count(*) from dosen')
            count = cursor.fetchone()[0]
            if(count>0):
                print("cek nik dosen")
                cursor.execute('select nik_dosen from dosen')
                cek_npm = cursor.fetchall()
                print(cek_npm[0][0])
                for p in cek_npm:
                    print(str(p[0])+" dan "+str(nomor_identitas))
                    if p[0] == nomor_identitas:
                        taken = True
                        break
                    else:
                        taken = False
            else:
                taken = False
        elif role == 'mahasiswa':
            cursor.execute('select count(*) from mahasiswa')
            count = cursor.fetchone()[0]
            if(count>0):
                print("cek nik dosen")
                cursor.execute('select npm from mahasiswa')
                cek_npm = cursor.fetchall()
                print(cek_npm[0][0])
                for p in cek_npm:
                    print(str(p[0])+" dan "+str(nomor_identitas))
                    if p[0] == nomor_identitas:
                        taken = True
                        break
                    else:
                        taken = False
            else:
                taken = False

        elif role == 'staf':
            cursor.execute('select count(*) from staf')
            count = cursor.fetchone()[0]
            if(count>0):
                print("cek nik dosen")
                cursor.execute('select nik_staf from staf')
                cek_npm = cursor.fetchall()
                print(cek_npm[0][0])
                for p in cek_npm:
                    print(str(p[0])+" dan "+str(nomor_identitas))
                    if p[0] == nomor_identitas:
                        taken = True
                        break
                    else:
                        taken = False
            else:
                taken = False
        else:
            no_role = True
    data = {
        'uname_is_taken' : taken,
        'cek_role' : no_role
    }
    return JsonResponse(data)

@csrf_exempt
def register_narasumber(request):
    print("masuk form")
    form = RegisterForm(data=request.POST)
    print("hai")
    print(request.method)
    print(form.is_valid())
    print(form.errors)
    if (request.method == 'POST' and form.is_valid()):
        print("hai juga")
        cursor = connection.cursor()
        cursor.execute('select count(*) from narasumber')
        count = cursor.fetchone()[0] #(2,)
        id_narasumber = 0
        if count > 0:
            id_narasumber = count + 1
        else:
            id_narasumber = 1
        username = request.POST.get('username', False)#request.POST.get['username']
        password = request.POST.get('password', False)
        nama = request.POST.get('nama', False)
        role = request.POST.get('role', False)
        nomor_identitas = request.POST.get('nomor_identitas', False)
        email = request.POST.get('email', False)
        no_hp = request.POST.get('no_hp', False)
        tempat = request.POST.get('tempat', False)
        tanggal = request.POST.get('tanggal', False)
        status = request.POST.get('status', False)
        jurusan = request.POST.get('jurusan', False)
        posisi = request.POST.get('posisi', False)
        print(status)
        id_universitas = request.POST.get('id_universitas', False)

        query_mhs_lg = "insert into MAHASISWA (id_narasumber,npm,status) values ("+str(id_narasumber)+", "+"'"+str(nomor_identitas)+"'"+", "+"'"+str(status)+"')"
        query_dosen = "insert into DOSEN (id_narasumber,nik_dosen,jurusan) values ("+str(id_narasumber)+", "+"'"+str(nomor_identitas)+"'"+", "+"'"+str(jurusan)+"')"
        query_staf = "insert into STAF (id_narasumber,nik_staf,posisi) values ("+str(id_narasumber)+", "+"'"+str(nomor_identitas)+"'"+", "+"'"+str(posisi)+"')"
        print(query_mhs_lg)
        print(query_dosen)
        print(query_staf)

        if role == 'dosen' or role == 'staf' or role == 'mahasiswa':
            print(id_universitas)
            query = "insert into NARASUMBER (id, nama, email, tempat, tanggal, no_hp, id_universitas, username, password) values ("+str(id_narasumber)+", "+"'"+str(nama)+"'"+", "+"'"+str(email)+"'"+", "+"'"+str(tempat)+"'"+", "+"'"+str(tanggal)+"'"+", "+"'"+str(no_hp)+"'"+", "+str(id_universitas)+", "+"'"+str(username)+"'"+", "+"'"+str(password)+"')"
            print(query)
            cursor.execute(query)

        if role == 'mahasiswa':
            cursor.execute(query_mhs_lg)
        elif role == 'dosen':
            cursor.execute(query_dosen)
        elif role == 'staf':
            cursor.execute(query_staf)
        messages.success(request, "Selamat! Anda berhasil mendaftar! Silakan login kembali untuk melanjutkan")
        return HttpResponseRedirect(reverse('apps-login:login'))
    else:
        return HttpResponse("null")

app_2/templates/app_2/register.html
{% extends "bmnc5d/layout/baseAwal.html" %}
{% load staticfiles %}

{% block style %}
<style type="text/css">
  .btn {
    font-size: 16px;
  }
  h5 {
    font-size: 18px;
  }
  #judul {
    font-size: 18px;
  }
  h2 {
    font-size: 24px;
  }
</style>
{% endblock %}

{% block content %}
<div class="py-5" style="background-image:url(https://i.pinimg.com/originals/fc/05/09/fc050933c0b1056dd78bc25e447da02a.jpg); background-size:cover;">
    <div class="container">
      <div class="row">
        <div class="align-self-center col-md-3 text-white">
          <h1 class="text-center text-md-left display-3">BMNC</h1>
          <p class="lead">Register now and write your news</p>
        </div>
        <div class="col-md-9">
          <div class="card">
            <div class="card-body p-5">
              <form method="POST" action="{% url 'register-narasumber' %}">
                {% csrf_token %}
                {% if reg_form.errors %}
                  <div class="alert alert-error">
                      <ul>
                          {% for error in reg_form.non_field_errors %}
                              <li>{{ error }}</li>
                          {% endfor %}
                      </ul>
                  </div>
              {% endif %}
                <div class="row">
                  <div class="mb-3">
                    <div class="form-group">
                      <label for="{{ reg_form.username.id_for_label }}">{{reg_form.username.label}}<span style="color:red">*</span></label>
                      {{reg_form.username}}
                      <div class="notif">
                        <small>Username yang anda masukkan tidak tersedia. Coba yang lain.</small>
                      </div>
                    </div>
                  </div>
                  <div class="mb-3">
                    <div class="form-group">
                      <label for="{{ reg_form.password.id_for_label }}">{{reg_form.password.label}}<span style="color:red">*</span></label>
                      {{reg_form.password}}
                      <div class="notif-pwd">
                      </div>
                    </div>
                  </div>
                </div>
                <hr class="style14" style="opacity:0.4">
                <div class="row">
                  <div class="mb-3">
                    <div class="form-group">
                      <label for="{{ reg_form.role.id_for_label }}">{{reg_form.role.label}}<span style="color:red">*</span></label>
                      {{reg_form.role}}
                    </div>
                  </div>
                  <div class="mb-3>
                    <div class="form-group">
                      <label for="{{ reg_form.nomor_identitas.id_for_label }}">{{reg_form.nomor_identitas.label}}<span style="color:red">*</span></label>
                      {{reg_form.nomor_identitas}}
                      <div class="notif-npm">
                        <small>Nomor identitas yang anda masukkan tidak tersedia. Coba yang lain.</small>
                      </div>
                      <div class="notif-role">
                        <small>Harap isi <i>field</i> Role terlebih dahulu sebelum mengisi nomor identitas</small>
                      </div>
                    </div>
                  </div>
                </div>
                <hr class="style14" style="opacity:0.4">
                <div class = "mb-3">
                  <div class="form-group">
                    <label for="{{ reg_form.nama.id_for_label }}">{{reg_form.nama.label}}<span style="color:red">*</span></label>
                    {{reg_form.nama}}
                  </div>
                </div>
                  <div class="mb-3">
                    <div class="form-group">
                      <label for="{{ reg_form.email.id_for_label }}">{{reg_form.email.label}}<span style="color:red">*</span></label>
                      {{reg_form.email}}
                    </div>
                  </div>
                  <div class="mb-3">
                    <div class="form-group">
                      <label for="{{ reg_form.no_hp.id_for_label }}">{{reg_form.no_hp.label}}</label>
                      {{reg_form.no_hp}}
                    </div>
                  </div>
                  <div class="mb-3">
                    <div class="form-group">
                      <label for="{{ reg_form.tempat.id_for_label }}">{{reg_form.tempat.label}}<span style="color:red">*</span></label>
                      {{reg_form.tempat}}
                    </div>
                  </div>
                  <div class="mb-3">
                    <div class="form-group">
                      <label for="{{ reg_form.tanggal.id_for_label }}">{{reg_form.tanggal.label}}<span style="color:red">*</span></label>
                      {{reg_form.tanggal}}
                    </div>
                  </div>                
                  <hr class="style14" style="opacity:0.4">
                <!--if dosen or staf-->
                <div class="form-group" id="univ">
                  <label for="{{ reg_form.id_universitas.id_for_label }}">{{reg_form.id_universitas.label}}<small style="color:red">*</small></label>
                  {{reg_form.id_universitas}}
                  <div class="notif-status">
                    <small>Harap isi <i>field</i> Role terlebih dahulu.</small>
                  </div>
                </div>
                <!--if mahasiswa-->
                <div class="form-group" id="status">
                  <label for="{{ reg_form.status.id_for_label }}">{{reg_form.status.label}}<small id="wajibstatus" style="color:red">*</small></label>
                  {{reg_form.status}}
                  <div class="notif-status">
                    <small>Harap isi <i>field</i> Role terlebih dahulu.</small>
                  </div>
                </div>
                <div class="form-group" id="jurusan">
                  <label for="{{ reg_form.jurusan.id_for_label }}">{{reg_form.jurusan.label}}<small id="wajibjurusan" style="color:red">*</small></label>
                  {{reg_form.jurusan}}
                  <div class="notif-status">
                    <small>Harap isi <i>field</i> Role terlebih dahulu.</small>
                  </div>
                </div>
                <div class="form-group" id="posisi">
                  <label for="{{ reg_form.posisi.id_for_label }}">{{reg_form.posisi.label}}<small id="wajibposisi" style="color:red">*</small></label>
                  {{reg_form.posisi}}
                  <div class="notif-status">
                    <small>Harap isi <i>field</i> Role terlebih dahulu.</small>
                  </div>
                </div> 
                <hr class="style14" style="opacity:0.1">
                <div class="row">
                  <div class="col-sm-12">
                  <button class="btn btn-secondary btn-lg btn-block" type="submit">Register</button>
                </div>
              </form>
              <p class="">Already have an account?
              <a class="text-dark" href="/login">Log In</a>
            </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="">
      <div class="container">
        <div class="row">
          <div class="col-md-12 order-md-1"> </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

{% block javascript %}
<!--<select name="one" onchange="if (this.value=='other'){this.form['other'].style.visibility='visible'}else {this.form['other'].style.visibility='hidden'};">-->
<script type="text/javascript">
$(document).ready(function(){
  $('#id_role').change(function() {
    //$("#id_status").attr('disabled',false)
    $("#id_nomor_identitas").attr('disabled',false)
    $('.notif-role').css('display','none');
    $('.notif-status').css('display','none');
    $("#id_id_universitas").attr('disabled',false);
    //$("#id_posisi").attr('disabled',true);
    $("#id_posisi").attr({disabled: true, required: false});
    $("#id_jurusan").attr({disabled: true, required: false});
    $("#id_status").attr({disabled: true, required: false});
    //$("#id_jurusan").attr('disabled',true);
    $('#wajibstatus').css('display','inline-block');
    $('#wajibposisi').css('display','inline-block');
    $('#wajibjurusan').css('display','inline-block');

    $('#jurusan').css('display','none');
    $('#status').css('display','none');
    $('#posisi').css('display','none');
    console.log(this.value);
    if (this.value == 'dosen') {
      //$("#id_status").attr('disabled',true)
      $("#id_jurusan").attr({disabled: false, required: true});
      $('#wajibstatus').css('display','none');
      $('#wajibposisi').css('display','none');
      $('#jurusan').css('display','block');
    }
    else if(this.value == 'staf') {
      //$("#id_status").attr('disabled',true)
      $("#id_posisi").attr({disabled: false, required: true});
      $('#wajibstatus').css('display','none');
      $('#wajibjurusan').css('display','none');
      $('#posisi').css('display','block');
    }
    else if (this.value == 'mahasiswa') {
      $("#id_status").attr({disabled: false, required: true});
      $('#wajibjurusan').css('display','none');
      $('#wajibposisi').css('display','none');
      $('#status').css('display','block');
    }
  })
  $('#id_username').change(function() {
    $('.notif').css('display','none');
    username = $(this).val();
    $.ajax({
      method: "POST",
      url: '{% url "validate-username" %}',
      data: {
        'username': username
      },
      dataType: 'json',
      success: function(data) {
        console.log(data)
        if (data.uname_is_taken) {
          $('.notif').css('display','block');
        }
      },
      error: function (rs, e) {
          alert(rs.responseText);
      }
    })
  })
  $('#id_nomor_identitas').change(function() {
    $('.notif-npm').css('display','none');
    $('.notif-role').css('display','none');
    npm = $(this).val();
    role = $('#id_role').val();
    url_validate = "/login/validate-npm/";
    console.log(url_validate)
    $.ajax({
      method: "POST",
      url: url_validate,
      data: {
        'npm': npm,
        'role': role
      },
      dataType: 'json',
      success: function(data) {
        console.log(data)
        if (data.uname_is_taken) {
          $('.notif-npm').css('display','block');
        }
      },
      error: function (rs, e) {
          alert(rs.responseText);
      }
    })
  })
  $('#id_password').change(function() {
    $('.notif-pwd').css('display','none');
    password = $(this).val();
    $.ajax({
      method: "POST",
      url: '{% url "validate-pwd" %}',
      data: {
        'password': password
      },
      dataType: 'json',
      success: function(data) {
        console.log(data)
        if (data.list_of_notif.length>0) {
          console.log(data.list_of_notif)
          $('.notif-pwd').css('display','block');
          for (i = 0; i<data.list_of_notif.length; i++) {
            var txt = "<p><small>"+data.list_of_notif[i]+"</small></p>";
            console.log(txt);
            $('.notif-pwd').append(txt)
          }
        }
      },
      error: function (rs, e) {
          alert(rs.responseText);
      }
    })
  })
})

</script>
{% endblock %}